version: '3.9'
services:
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    volumes:
      - .:/myapp
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - "test=${test}"